name: deploy.yaml

on:
  push:
    branches:
      - main

concurrency: preview-${{ github.ref }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
