name: Sync Obsidian Vault Submodule

on:
  push:
    branches: [ main ]
    paths:
      - 'website/**'
  workflow_dispatch:

jobs:
  sync-submodule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: false

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add or Update Submodule
        run: |
          git submodule add -f https://github.com/wtf403/obsidian.git wtf403
          git submodule update --remote wtf403

      - name: Commit Changes
        run: |
          git add wtf403
          git commit -m "Update submodule" || echo "No changes to commit"

      - name: Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin main